### ISSUE TITLE
[FR] - named routes and  "route" template tag

### ISSUE THREAD

**Issue by piotrpog** [miranj/craft-router#1]
Since your plugin handles routes, I think it might be a good place to include such functionality. I described it earlier in feature request fro Craft, so I will just paste a link:

https://github.com/craftcms/cms/issues/3308

By the way, are there any plans for including this plugin in plugin store?

**Comment by rungta** [comment]
Sounds like a useful feature. Will take a deeper look when I have the time, no promises. 

> By the way, are there any plans for including this plugin in plugin store?

Yes, we indend to. Hoping to refactor some bits and improve documentation before adding it to the store. You can install it via composer in the meantime. We’ve been using it on a bunch of Craft 3 projects.
