### ISSUE TITLE
Breaks on third segment when solo

### ISSUE THREAD

**Issue by cap-akimrey** [miranj/craft-router#2]
Hi, Prateek

This plugin presents a graceful solution, however I've hit upon an issue in my testing. The reading of the criteria area seems to get thrown off on a third segment. I haven't tested beyond 3.

My router.php file contents:

```
<?php
/* config/router.php */

return [
  'rules' => [
    'archive' => [
        'segments' => [
            '<year:\d{4}>',
            '<foodType:{slug}>',
            '<color:{slug}>',
        ],

        'criteria' => [
            'year' => [
                'type' => 'year',
                'field' => 'postDate',
            ],
            'foodType' => [
                'type' => 'entry',
                'section' => 'foodTypes',
            ],
            'color' => [
                'type' => 'category',
                'group' => 'colors',
            ],
        ],

        'template' => '_private/archive',
      ]
  ],
];

```
http://starter-blog.test/archive/2020 works fine.
http://starter-blog.test/archive/2020/fruits works fine.
http://starter-blog.test/archive/2020/fruits/red works fine.
http://starter-blog.test/archive/fruits/red works fine.

http://starter-blog.test/archive/red breaks.
http://starter-blog.test/archive/2020/red breaks.

Below is the stack trace, and I've attached screenshots of the various scenarios.

Craft Pro 3.5.12.1
Router 1.0.0
PHP 7.2

> yii\web\NotFoundHttpException in /Users/akimrey/Sites/starter-blog/vendor/miranj/craft-router/src/controllers/DefaultController.php:223
> Stack trace:
> #0 [internal function]: miranj\router\controllers\DefaultController->actionIndex('_private/archiv...', Array, Array)
> #1 /Users/akimrey/Sites/starter-blog/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
> #2 /Users/akimrey/Sites/starter-blog/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
> #3 /Users/akimrey/Sites/starter-blog/vendor/craftcms/cms/src/web/Controller.php(189): yii\base\Controller->runAction('index', Array)
> #4 /Users/akimrey/Sites/starter-blog/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('index', Array)
> #5 /Users/akimrey/Sites/starter-blog/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('router/default/...', Array)
> #6 /Users/akimrey/Sites/starter-blog/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('router/default/...', Array)
> #7 /Users/akimrey/Sites/starter-blog/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
> #8 /Users/akimrey/Sites/starter-blog/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
> #9 /Users/akimrey/Sites/starter-blog/web/index.php(21): yii\base\Application->run()
> #10 /Users/akimrey/.composer/vendor/laravel/valet/server.php(158): require('/Users/akimrey/...')
> #11 {main}

Btw, I enjoyed your presentation in Montreal. Such a hot weekend, though.

Thanks
Alan

![color(3) segment](https://user-images.githubusercontent.com/41020122/95877134-685aa500-0d39-11eb-87dd-98b06081154e.png)
![year(1) type(2) color(3) segments](https://user-images.githubusercontent.com/41020122/95877136-68f33b80-0d39-11eb-97aa-f6f0f7ea7e36.png)
![type(2) color(3) segments](https://user-images.githubusercontent.com/41020122/95877138-68f33b80-0d39-11eb-957e-b0d72a549824.png)
![type(2) segment](https://user-images.githubusercontent.com/41020122/95877139-698bd200-0d39-11eb-8746-5623c495f4a5.png)
![year(1) type(2) segments](https://user-images.githubusercontent.com/41020122/95877140-698bd200-0d39-11eb-8c63-04581c4347cb.png)
![year(1) segment](https://user-images.githubusercontent.com/41020122/95877142-698bd200-0d39-11eb-8996-a75d7048e09a.png)

**Comment by rungta** [comment]
Hi Alan! Glad to hear you liked my presentation. Hope we’re all able to travel to another Dot All again.

The issue you’re running into is due to the fact that the second and third segments both have the same regular expression.

```php
'segments' => [
  '<year:\d{4}>',
  '<foodType:{slug}>',
  '<color:{slug}>',
],
```

If you take a URL such as `/2020/fruits/red`, then the existence of all 3 segments ensures that `fruits` is matched as a `foodType` while `red` is matched as `color`. However, when you have just one or two segments, such as in `/2020/red` or `/red` then the match is for `foodType`, not `color`. In order to work around this issue, I would recommend adding some sort of prefix so that a food type is not mistaken for a color, and vice-versa. Eg:

```php
'segments' => [
  '<year:\d{4}>',
  'type:<foodType:{slug}>',
  '<color:{slug}>',
],
```

So your URLs will now change from `/2020/fruits/red` to `/2020/type:fruits/red`. Not as pretty but unfortunately I do not have a better workaround at the moment.

**Comment by cap-akimrey** [comment]
Thanks for the details. It works as you suggest.
